const fs = require("fs");
exports.dare = [
  'Post selfie lucu di Instagram tanpa penjelasan.',
  'Kirim pesan ke seseorang di daftar kontakmu dan katakan "Aku tahu rahasiamu" tanpa penjelasan.',
  'Buat tweet lucu tentang makanan yang kamu makan hari ini.',
  'Ganti foto profilmu di media sosial dengan gambar karakter anime selama 24 jam.',
  'Kirim pesan kepada seseorang yang kamu follow di media sosial dan minta rekomendasi film favoritnya.',
  'Buat story Instagram dengan lagu yang dipilih temanmu tanpa memberi tahu alasan mengapa kamu memilih lagu tersebut.',
  'Kirim pesan ke temanmu dan minta dia memberi kamu saran emoji yang paling mencerminkan kepribadianmu.',
  'Buat postingan Facebook yang menjelaskan alasan kamu suka bermain Truth or Dare di media sosial.',
  'Kirim pesan ke seseorang di daftar teman Facebookmu dan ajak dia bermain game online apa pun.',
  'Buat caption kreatif untuk foto profilmu di media sosial tanpa menggunakan emoji.',
  'Ganti status WhatsAppmu dengan kalimat "Saya adalah manusia robot" selama 2 jam.',
  'Kirim pesan ke temanmu dan minta dia memberi kamu saran judul blog yang menarik.',
  'Buat postingan TikTok tentang hewan peliharaan virtualmu (jika kamu punya) dan berikan nama serta ceritakan kepribadiannya.',
  'Buat postingan Instagram dengan foto tumpukan buku di rumahmu dan tulis caption tentang buku favoritmu.',
  'Kirim pesan ke salah satu kontak di WhatsAppmu dan ajak dia untuk berbagi fakta unik tentang dirinya.',
  'Buat thread di Twitter tentang hal favoritmu dalam bermain Truth or Dare.',
  'Ganti foto profilmu di media sosial dengan gambar makanan yang paling menggugah selera.',
  'Buat postingan Facebook yang mengajak teman-temanmu untuk memberikan rekomendasi film terbaik mereka.',
  'Kirim pesan ke salah satu temanmu dan ajak dia untuk berbicara dalam bahasa Inggris selama 30 menit.',
  'Buat video pendek di TikTok yang memperkenalkan dirimu dengan cara yang unik.',
  'Kirim pesan kepada temanmu dan minta dia memberi saran untuk caption foto profilmu di media sosial.',
  'Buat postingan Instagram tentang hal paling lucu yang pernah kamu alami di media sosial.',
  'Ganti status WhatsAppmu dengan kutipan lucu dari film selama 3 jam.',
  'Kirim pesan ke temanmu dan minta dia memberi kamu saran tentang hobi baru yang bisa kamu coba.',
  'Buat tweet tentang hal paling aneh yang pernah kamu lihat di media sosial.',
  'Buat postingan Facebook tentang acara TV atau film yang paling kamu nantikan.',
  'Kirim pesan kepada salah satu kontak di WhatsAppmu dan minta dia memberi kamu saran lagu untuk didengarkan.',
  'Buat video di TikTok tentang rutinitas harianmu dengan gaya yang lucu.',
  'Kirim pesan ke salah satu temanmu dan ajak dia untuk berbicara dengan aksen selama 10 menit.',
  'Buat postingan Instagram tentang tempat yang ingin kamu kunjungi selanjutnya dan kenapa kamu ingin pergi ke sana.',
  'Ganti foto profilmu di media sosial dengan gambar karakter kartun favoritmu selama 24 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu saran tentang buku yang harus kamu baca.',
  'Buat story di Instagram dengan meme lucu tanpa memberi tahu alasannya.',
  'Ganti status WhatsAppmu dengan foto selfie lucu selama 2 jam.',
  'Kirim pesan kepada salah satu temanmu dan minta dia memberi kamu saran tentang resep makanan yang harus kamu coba.',
  'Buat postingan Facebook yang mengajak teman-temanmu untuk berbagi cerita tentang liburan terbaik mereka.',
  'Buat video di TikTok tentang hewan peliharaanmu dan ceritakan kejenakaannya.',
  'Kirim pesan ke salah satu kontak di WhatsAppmu dan ajak dia bermain game tebak-tebakan.',
  'Buat postingan Instagram tentang hal teraneh yang pernah kamu lakukan di akun media sosialmu.',
  'Ganti foto profilmu di media sosial dengan gambar hewan peliharaan (jika kamu punya) selama 24 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu saran tentang tempat makan baru yang harus kamu coba.',
  'Buat story di Instagram dengan pantun lucu tentang dirimu sendiri.',
  'Ganti status WhatsAppmu dengan kalimat "Saya adalah seorang pahlawan super" selama 3 jam.',
  'Kirim pesan kepada salah satu temanmu dan ajak dia berbicara dalam bahasa asing selama 15 menit.',
  'Buat postingan Facebook yang mengajak teman-temanmu untuk memberikan rekomendasi game online yang seru.',
  'Buat video di TikTok tentang hal favoritmu dalam bermain Truth or Dare dan mengapa kamu suka permainan ini.',
  'Kirim pesan ke salah satu kontak di WhatsAppmu dan minta dia memberi kamu saran film yang harus kamu tonton.',
  'Buat postingan Instagram tentang hal paling konyol yang pernah kamu alami saat menggunakan media sosial.',
  'Ganti foto profilmu di media sosial dengan gambar makanan favoritmu selama 24 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu saran tentang tempat liburan yang harus kamu kunjungi.',
  'Buat story di Instagram dengan video singkat tentang hal lucu yang terjadi hari ini.',
  'Ganti status WhatsAppmu dengan kutipan motivasi selama 2 jam.',
  'Kirim pesan kepada salah satu temanmu dan ajak dia berbicara dalam bahasa khas daerahmu selama 10 menit.',
  'Buat postingan Facebook tentang hal paling aneh yang pernah kamu temukan di media sosial.',
  'Buat video di TikTok yang memperkenalkan temanmu dengan cara yang lucu.',
  'Kirim pesan ke salah satu kontak di WhatsAppmu dan minta dia memberi kamu saran podcast yang menarik.',
  'Buat thread di Twitter tentang hobi unikmu.',
  'Kirim pesan ke kontak WhatsAppmu yang ada di urutan ke-10 dan katakan padanya bahwa dia adalah teman terbaikmu.',
  'Buat story Instagram dengan lagu yang kamu dengarkan saat ini tanpa memberikan konteks.',
  'Ganti foto profilmu di media sosial dengan gambar hewan peliharaan (jika ada) selama 12 jam.',
  'Kirim pesan kepada seseorang di daftar teman Facebookmu dan minta dia memberi kamu rekomendasi buku yang mengubah hidupnya.',
  'Buat tweet lucu tentang kebiasaan buruk yang ingin kamu tinggalkan.',
  'Kirim pesan ke salah satu kontak di WhatsAppmu dan ajak dia bermain permainan teka-teki.',
  'Buat postingan Instagram tentang film terakhir yang membuatmu menangis.',
  'Ganti status WhatsAppmu dengan kutipan dari film favoritmu selama 4 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu saran lagu untuk playlist "Semangat Pagi".',
  'Buat video di TikTok yang mengajak temanmu untuk menari lagu terpopuler saat ini.',
  'Kirim pesan ke salah satu temanmu dan ajak dia berbicara tentang kegemaran musikmu selama 20 menit.',
  'Buat story di Instagram tentang hal paling aneh yang pernah kamu beli secara online.',
  'Ganti foto profilmu di media sosial dengan gambar karakter superhero favoritmu selama 12 jam.',
  'Kirim pesan kepada seseorang di daftar teman Facebookmu dan minta dia memberi kamu rekomendasi restoran terbaik di kota tempat tinggalmu.',
  'Buat tweet tentang hal paling konyol yang pernah kamu lihat di media sosial.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi aplikasi yang berguna.',
  'Buat postingan Facebook tentang buku yang saat ini kamu baca dan mengapa kamu suka buku itu.',
  'Ganti status WhatsAppmu dengan foto meme lucu selama 3 jam.',
  'Kirim pesan ke salah satu kontak di WhatsAppmu dan ajak dia untuk membuat daftar acara TV yang harus kamu tonton.',
  'Buat postingan Instagram tentang makanan yang kamu impikan saat ini.',
  'Buat video di TikTok yang menunjukkan trik sulap sederhana.',
  'Kirim pesan ke salah satu temanmu dan ajak dia berbicara tentang hobi yang kamu ingin coba.',
  'Buat story di Instagram dengan foto yang paling menggugah selera makananmu hari ini.',
  'Ganti foto profilmu di media sosial dengan gambar makanan favoritmu selama 12 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu saran film komedi yang lucu.',
  'Buat postingan Facebook tentang tempat liburan impianmu dan kenapa kamu ingin pergi ke sana.',
  'Buat video di TikTok yang mengajak temanmu untuk bermain Truth or Dare.',
  'Kirim pesan ke salah satu kontak di WhatsAppmu dan ajak dia berbicara dalam bahasa Inggris selama 15 menit.',
  'Buat postingan Instagram tentang hal teraneh yang pernah kamu lakukan saat bepergian.',
  'Ganti status WhatsAppmu dengan kutipan dari buku favoritmu selama 4 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi podcast yang paling kamu suka.',
  'Buat story di Instagram dengan meme lucu tentang media sosial.',
  'Ganti foto profilmu di media sosial dengan gambar tempat wisata impianmu selama 12 jam.',
  'Kirim pesan kepada salah satu temanmu dan ajak dia berbicara tentang acara TV favoritmu.',
  'Buat postingan Facebook tentang hal paling lucu yang pernah kamu alami di media sosial.',
  'Buat video di TikTok yang memperkenalkan hewan peliharaanmu (jika ada) dan ceritakan tingkah lucunya.',
  'Kirim pesan ke salah satu kontak di WhatsAppmu dan minta dia memberi kamu rekomendasi aplikasi yang cocok untuk hobi baru yang ingin kamu coba.',
  'Buat postingan Instagram tentang hal paling aneh yang pernah kamu temukan di toko online.',
  'Ganti foto profilmu di media sosial dengan gambar teknologi masa depan selama 12 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi restoran dengan makanan terenak.',
  'Buat story di Instagram tentang hal lucu yang terjadi hari ini.',
  'Ganti status WhatsAppmu dengan kutipan motivasi dari tokoh terkenal selama 3 jam.',
  'Kirim pesan kepada salah satu temanmu dan ajak dia berbicara dalam bahasa asing selama 10 menit tentang film-film yang kamu suka.',
  'Buat postingan Facebook tentang acara TV yang paling kamu nantikan.',
  'Buat video di TikTok yang mengajak temanmu untuk berbicara tentang film favoritmu.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi buku dengan cerita seru.',
  'Buat story di Instagram dengan video singkat tentang cara kamu membuat makanan favoritmu.',
  'Ganti foto profilmu di media sosial dengan gambar alam yang indah selama 12 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi lagu untuk playlist "Malam Romantis".',
  'Buat postingan Instagram tentang hal teraneh yang pernah kamu impikan.',
  'Ganti status WhatsAppmu dengan foto selfie lucu selama 3 jam.',
  'Kirim pesan kepada salah satu kontak di WhatsAppmu dan ajak dia bermain permainan teka-teki.',
  'Buat postingan Facebook tentang hal paling konyol yang pernah kamu lihat di media sosial.',
  'Buat video di TikTok yang mengajak temanmu untuk menari lagu favoritmu.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi film thriller yang seram.',
  'Buat story di Instagram tentang hal paling lucu yang pernah kamu alami di media sosial.',
  'Ganti foto profilmu di media sosial dengan gambar hewan peliharaan (jika kamu punya) selama 12 jam.',
  'Kirim pesan kepada salah satu temanmu dan ajak dia berbicara tentang tempat liburan impianmu.',
  'Buat postingan Instagram tentang makanan yang kamu idamkan saat ini.',
  'Ganti status WhatsAppmu dengan kutipan dari film komedi favoritmu selama 4 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi lagu untuk playlist "Pergi Jogging".',
  'Buat video di TikTok yang menunjukkan trik sulap sederhana yang bisa kamu lakukan.',
  'Kirim pesan kepada salah satu kontak di WhatsAppmu dan ajak dia untuk membuat daftar film yang harus kamu tonton.',
  'Buat postingan Facebook tentang hal paling aneh yang pernah kamu lakukan saat bepergian.',
  'Buat story di Instagram tentang tempat wisata impianmu dan kenapa kamu ingin pergi ke sana.',
  'Ganti foto profilmu di media sosial dengan gambar hewan peliharaan (jika ada) selama 12 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi aplikasi yang berguna dalam kehidupan sehari-hari.',
  'Buat postingan Instagram tentang hal teraneh yang pernah kamu beli secara online.',
  'Ganti status WhatsAppmu dengan kutipan dari buku yang sedang kamu baca selama 3 jam.',
  'Kirim pesan kepada salah satu temanmu dan ajak dia berbicara tentang hobi baru yang ingin kamu coba.',
  'Buat story di Instagram dengan foto yang paling menggugah selera makananmu hari ini.',
  'Ganti foto profilmu di media sosial dengan gambar teknologi masa depan selama 12 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi restoran dengan makanan terenak.',
  'Buat postingan Facebook tentang hal paling lucu yang pernah kamu alami di media sosial.',
  'Buat video di TikTok yang mengajak temanmu untuk bermain Truth or Dare.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi film dengan cerita seru.',
  'Buat story di Instagram tentang cara kamu membuat makanan favoritmu.',
  'Ganti status WhatsAppmu dengan foto alam yang indah selama 12 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi buku dengan cerita seru.',
  'Buat postingan Instagram tentang hal teraneh yang pernah kamu impikan.',
  'Ganti status WhatsAppmu dengan foto selfie lucu selama 3 jam.',
  'Kirim pesan kepada salah satu kontak di WhatsAppmu dan ajak dia bermain permainan teka-teki.',
  'Buat postingan Facebook tentang hal paling konyol yang pernah kamu lihat di media sosial.',
  'Buat video di TikTok yang mengajak temanmu untuk menari lagu favoritmu.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi film thriller yang seram.',
  'Buat story di Instagram tentang hal paling lucu yang pernah kamu alami di media sosial.',
  'Ganti foto profilmu di media sosial dengan gambar hewan peliharaan (jika kamu punya) selama 12 jam.',
  'Kirim pesan kepada salah satu temanmu dan ajak dia berbicara tentang tempat liburan impianmu.',
  'Buat postingan Instagram tentang makanan yang kamu idamkan saat ini.',
  'Ganti status WhatsAppmu dengan kutipan dari film komedi favoritmu selama 4 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi lagu untuk playlist "Pergi Jogging".',
  'Buat video di TikTok yang menunjukkan trik sulap sederhana yang bisa kamu lakukan.',
  'Kirim pesan kepada salah satu kontak di WhatsAppmu dan ajak dia untuk membuat daftar film yang harus kamu tonton.',
  'Buat postingan Facebook tentang hal paling aneh yang pernah kamu lakukan saat bepergian.',
  'Buat story di Instagram tentang tempat wisata impianmu dan kenapa kamu ingin pergi ke sana.',
  'Ganti foto profilmu di media sosial dengan gambar hewan peliharaan (jika ada) selama 12 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi aplikasi yang berguna dalam kehidupan sehari-hari.',
  'Buat postingan Instagram tentang hal teraneh yang pernah kamu beli secara online.',
  'Ganti status WhatsAppmu dengan kutipan dari buku yang sedang kamu baca selama 3 jam.',
  'Kirim pesan kepada salah satu temanmu dan ajak dia berbicara tentang hobi baru yang ingin kamu coba.',
  'Buat story di Instagram dengan foto yang paling menggugah selera makananmu hari ini.',
  'Ganti foto profilmu di media sosial dengan gambar teknologi masa depan selama 12 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi restoran dengan makanan terenak.',
  'Buat postingan Facebook tentang hal paling lucu yang pernah kamu alami di media sosial.',
  'Buat video di TikTok yang mengajak temanmu untuk bermain Truth or Dare.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi film dengan cerita seru.',
  'Buat story di Instagram tentang cara kamu membuat makanan favoritmu.',
  'Ganti status WhatsAppmu dengan foto alam yang indah selama 12 jam.',
  'Kirim pesan kepada temanmu dan minta dia memberi kamu rekomendasi buku dengan cerita seru.'
 ]