const fs = require("fs");
exports.truth = [
  'Apa rahasia paling lucu yang pernah kamu simpan?',
  'Apakah ada hal aneh yang kamu percayai sebagai kepercayaan takhayul?',
  'Siapa orang terakhir yang kamu kirimi pesan cinta diam-diam?',
  'Ceritakan momen paling memalukan dalam hidupmu!',
  'Jika kamu bisa menjadi hewan selama sehari, hewan apa yang akan kamu pilih?',
  'Apakah ada hal yang kamu inginkan untuk ubah dari dirimu sendiri?',
  'Jika kamu harus memilih antara selalu tertawa atau selalu tersenyum, mana yang akan kamu pilih?',
  'Apa hal teraneh yang pernah kamu makan?',
  'Kalau kamu bisa pergi ke masa lalu, ke acara sejarah apa kamu ingin pergi?',
  'Jika kamu bisa bertukar tempat dengan seseorang selama sehari, siapa yang akan kamu pilih?',
  'Apa hal paling aneh yang pernah kamu lakukan saat sedang sendirian di rumah?',
  'Kalau kamu bisa memiliki kekuatan super, apa yang ingin kamu miliki?',
  'Ceritakan mimpi paling aneh yang pernah kamu alami.',
  'Apa yang kamu lakukan jika kamu tiba-tiba menjadi selebriti terkenal?',
  'Jika kamu harus makan satu jenis makanan selama sebulan, apa yang akan kamu pilih?',
  'Apakah ada hal yang kamu lakukan secara rahasia tetapi tidak akan kamu katakan pada temanmu?',
  'Kalau kamu bisa berbicara dengan hewan, apa yang ingin kamu tanyakan pada mereka?',
  'Apa hal paling konyol yang pernah kamu takutkan?',
  'Jika kamu bisa memiliki satu keinginan sekarang juga, apa yang kamu inginkan?',
  'Kalau kamu bisa mengubah satu hukum di dunia, apa yang akan kamu ubah?',
  'Ceritakan pengalaman paling menegangkan yang pernah kamu alami!',
  'Apa yang akan kamu lakukan jika kamu bisa menginjak kaki di planet lain?',
  'Apakah ada hal yang kamu coba lakukan tetapi gagal total?',
  'Jika kamu harus hidup dalam film favoritmu, film apa yang akan kamu pilih?',
  'Apa yang paling kamu sukai dari dirimu sendiri?',
  'Ceritakan momen paling lucu yang pernah kamu alami.',
  'Jika kamu bisa memiliki kekuatan telepati, siapa yang pertama kali ingin kamu baca pikirannya?',
  'Kalau kamu bisa mengubah warna rambutmu dengan seketika, warna apa yang akan kamu pilih?',
  'Apa hal teraneh yang pernah kamu temukan di internet?',
  'Kalau kamu bisa menghabiskan sehari bersama tokoh sejarah, siapa yang akan kamu pilih?',
  'Apakah ada hal yang kamu tahu sekarang yang ingin kamu katakan pada dirimu sendiri di masa lalu?',
  'Jika kamu bisa menjadi karakter fiksi untuk sehari, siapa yang akan kamu pilih?',
  'Apa yang akan kamu lakukan jika kamu terjebak di taman hiburan sepanjang malam?',
  'Ceritakan impian paling aneh yang pernah kamu miliki.',
  'Jika kamu harus tinggal di tempat yang berbeda selama setahun, di mana kamu ingin tinggal?',
  'Apakah ada hal yang kamu lakukan ketika kamu masih kecil yang ingin kamu lakukan lagi sekarang?',
  'Kalau kamu bisa memiliki satu hewan peliharaan, hewan apa yang kamu pilih?',
  'Apa yang akan kamu lakukan jika kamu memiliki kemampuan untuk berbicara dengan tumbuhan?',
  'Ceritakan pengalaman paling seram yang pernah kamu alami!',
  'Jika kamu bisa memenangkan lotre, apa yang akan kamu lakukan dengan uangnya?',
  'Kalau kamu bisa tinggal di era sejarah tertentu, di era mana kamu ingin tinggal?',
  'Apakah ada hal aneh yang kamu ingin coba, tetapi belum pernah kamu coba sebelumnya?',
  'Apa yang akan kamu lakukan jika kamu bisa berhenti waktu selama satu jam?',
  'Ceritakan kisah paling aneh yang pernah kamu dengar.',
  'Kalau kamu bisa memiliki kemampuan untuk berbicara dengan objek mati, objek apa yang ingin kamu ajak bicara?',
  'Jika kamu bisa memiliki kekuatan untuk mengubah cuaca, cuaca apa yang akan kamu buat hari ini?',
  'Apa yang akan kamu lakukan jika kamu bisa memasuki dunia dalam buku favoritmu?',
  'Kalau kamu bisa memiliki satu super daya dari karakter superhero, apa yang akan kamu pilih?',
  'Ceritakan momen paling aneh yang pernah kamu alami di alam liar.',
  'Jika kamu bisa menjadi ahli dalam satu bidang dalam semalam, bidang apa yang akan kamu pilih?',
  'Apakah ada hal yang kamu ingin coba yang menakutkanmu?',
  'Apa yang akan kamu lakukan jika kamu terbangun sebagai hewan lain?',
  'Kalau kamu bisa memiliki mobil impianmu sekarang, mobil apa yang akan kamu pilih?',
  'Ceritakan pengalaman paling gila yang pernah kamu alami di perjalanan.',
  'Jika kamu bisa memiliki satu keahlian artistik, apa yang akan kamu pilih?',
  'Apa hal paling aneh yang pernah kamu temukan di alam liar?',
  'Kalau kamu bisa menjadi karakter dalam video game, karakter apa yang akan kamu pilih?',
  'Jika kamu bisa memerintahkan cuaca selama seminggu, cuaca apa yang akan kamu buat?',
  'Ceritakan kisah paling lucu yang pernah kamu alami bersama teman-temanmu.',
  'Kalau kamu bisa memiliki kekuatan untuk mengubah ukuran, apa yang akan kamu ubah?',
  'Apa yang akan kamu lakukan jika kamu tiba-tiba memiliki kemampuan untuk berbicara dengan hewan?',
  'Jika kamu bisa memiliki satu hal yang paling kamu impikan sekarang, apa itu?',
  'Apakah ada hal yang ingin kamu coba dalam hidupmu yang berhubungan dengan seni?',
  'Ceritakan momen paling gila yang pernah kamu alami di pesta.',
  'Kalau kamu bisa tinggal di dunia fantasi dari buku atau film, dunia apa yang akan kamu pilih?',
  'Jika kamu bisa menjadi benda mati selama sehari, benda apa yang akan kamu pilih?',
  'Apakah ada hal aneh yang kamu percayai sebagai takhayul yang membawa keberuntungan?',
  'Ceritakan pengalaman paling aneh yang pernah kamu alami di jalan.',
  'Apa makanan teraneh yang pernah kamu coba dan suka?',
  'Siapa tokoh sejarah yang ingin kamu ajak makan malam jika kamu bisa?',
  'Jika kamu bisa memiliki satu kekuatan super, apa yang akan kamu gunakan untuk?',
  'Apa lagu paling aneh yang ada di playlistmu, dan mengapa kamu suka lagu itu?',
  'Jika kamu bisa berbicara dengan hewan, apa pertanyaan pertama yang ingin kamu tanyakan pada hewan?',
  'Kalau kamu bisa mengubah warna langit, warna apa yang akan kamu pilih?',
  'Jika kamu bisa tinggal di film animasi selama sehari, film animasi apa yang akan kamu pilih?',
  'Ceritakan pengalaman paling lucu yang pernah kamu alami saat berkendara.',
  'Apa hewan peliharaan impianmu, dan apa namanya?',
  'Jika kamu bisa menjadi karakter video game, karakter video game apa yang akan kamu pilih?',
  'Jika kamu bisa memiliki satu kendaraan luar angkasa, seperti apa kendaraan itu?',
  'Ceritakan mimpi paling aneh yang pernah kamu alami tentang teknologi masa depan.',
  'Kalau kamu bisa memiliki satu kekuatan ilmiah, apa yang ingin kamu kuasai?',
  'Jika kamu bisa mengatur cuaca selama sebulan, apa cuaca yang akan kamu buat?',
  'Apa acara TV paling aneh yang pernah kamu nikmati, dan kenapa kamu suka acara itu?',
  'Jika kamu bisa tinggal di satu tempat di dunia yang penuh misteri, di mana itu?',
  'Ceritakan pengalaman paling aneh yang pernah kamu alami saat bepergian.',
  'Apa yang akan kamu lakukan jika kamu terbangun sebagai karakter dalam buku anak-anak?',
  'Jika kamu bisa menjadi seorang ilmuwan terkenal, bidang ilmu apa yang ingin kamu teliti?',
  'Jika kamu bisa memiliki satu hewan peliharaan fiksi, hewan apa yang akan kamu pilih?',
  'Ceritakan pengalaman terlucu yang pernah kamu alami di sekolah atau kuliah.',
  'Jika kamu bisa berbicara dengan tumbuhan, apa yang akan kamu tanyakan pada mereka?',
  'Kalau kamu bisa memiliki satu perjalanan waktu, ke acara sejarah apa yang ingin kamu pergi?',
  'Apa yang akan kamu lakukan jika kamu bisa berpindah ke dunia video game favoritmu?',
  'Jika kamu bisa memiliki satu gadget futuristik, gadget apa yang akan kamu pilih?',
  'Ceritakan mimpi paling konyol yang pernah kamu alami tentang petualangan ruang angkasa.',
  'Jika kamu bisa menjadi pahlawan super, nama pahlawan supermu apa?',
  'Jika kamu bisa menjadi guru, mata pelajaran apa yang ingin kamu ajarkan?',
  'Ceritakan momen paling menegangkan yang pernah kamu alami saat naik roller coaster.',
  'Jika kamu bisa memiliki satu keahlian seni, apa yang ingin kamu kuasai?',
  'Jika kamu bisa memenangkan lotre besar, apa yang akan menjadi proyek impianmu?',
  'Ceritakan pengalaman paling seram yang pernah kamu alami saat berkemah di hutan.',
  'Jika kamu bisa tinggal di satu tempat di dunia yang sepenuhnya terisolasi, di mana itu?',
  'Kalau kamu bisa memiliki kekuatan untuk membuat makanan muncul dari udara, makanan apa yang akan kamu pilih?',
  'Jika kamu bisa menjadi karakter dalam film horor, karakter apa yang akan kamu pilih?',
  'Apa yang akan kamu lakukan jika kamu bisa terbangun sebagai binatang di kebun binatang?',
  'Ceritakan kisah paling aneh yang pernah kamu dengar tentang makhluk supernatural.',
  'Jika kamu bisa memiliki satu kekuatan alam yang dapat mengendalikan alam, apa yang akan kamu pilih?',
  'Jika kamu bisa menjadi arkeolog terkenal, apa penemuan sejarah yang ingin kamu temukan?',
  'Ceritakan mimpi paling aneh yang pernah kamu alami tentang petualangan bawah laut.',
  'Jika kamu bisa menjadi karakter dalam satu buku yang kamu baca, buku apa yang akan kamu pilih?',
  'Apa yang akan kamu lakukan jika kamu tiba-tiba dapat berbicara dengan hantu?',
  'Jika kamu bisa memiliki satu kendaraan di dunia fiksi, kendaraan apa yang akan kamu pilih?',
  'Kalau kamu bisa mengubah dirimu menjadi monster fiksi, monster apa yang akan kamu jadiin?',
  'Jika kamu bisa menjadi penulis terkenal, genre apa yang ingin kamu tulis?',
  'Ceritakan kisah paling lucu yang pernah kamu alami saat berkemah di pantai.',
  'Jika kamu bisa memiliki satu senjata ilmiah, senjata apa yang akan kamu pilih?',
  'Jika kamu bisa memiliki satu restoran yang sangat unik, restoran seperti apa yang akan kamu buka?',
  'Apa yang akan kamu lakukan jika kamu tiba-tiba memiliki kemampuan untuk berbicara dengan alien?',
  'Jika kamu bisa tinggal di era sejarah yang sangat jauh, di era apa yang ingin kamu tinggali?',
  'Ceritakan pengalaman paling konyol yang pernah kamu alami saat mendaki gunung.',
  'Jika kamu bisa memiliki satu perangkat futuristik, perangkat apa yang akan kamu pilih?',
  'Jika kamu bisa menjadi karakter dalam film komedi, karakter apa yang akan kamu pilih?',
  'Apa yang akan kamu lakukan jika kamu terbangun sebagai karakter dalam permainan papan?',
  'Jika kamu bisa memiliki satu kekuatan magis, apa yang akan kamu gunakan untuk?',
  'Ceritakan kisah paling aneh yang pernah kamu dengar tentang eksperimen ilmiah.',
  'Jika kamu bisa memiliki satu gadget canggih, gadget apa yang akan kamu pilih?'
  ]